version: "3.9"
# ref: https://docs.docker.com/compose/compose-file
services:
  app:
    image: goplanner
    build:
      args:
        - target=dev
    environment:
      PLANNER_ENV: dev
      PORT: 8080
      PLANNER_DB_HOST: planner-db
      PLANNER_DB_PORT: 3306
      PLANNER_DB_USER: planner
      PLANNER_DB_PASSWORD: planner
      PLANNER_DB_NAME: planner
      PLANNER_REDIS_HOST: planner-redis
      PLANNER_REDIS_PORT: 6379
    volumes:
      - .:/app
    ports:
      - "18000:8080"
  planner-db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: planner-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: planner
      MYSQL_PASSWORD: planner
      MYSQL_DATABASE: planner
    volumes:
      - planner-db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "36306:3306"
    command: mysqld --innodb_use_native_aio=0
  planner-redis:
    image: "redis:latest"
    container_name: planner-redis
    ports:
      - "36379:6379"
    volumes:
      - planner-redis-data:/data
volumes:
  planner-db-data:
  planner-redis-data:
